name: CI/CD Pipeline for Login App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/login-app:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/login-app:latest ${{ secrets.DOCKER_USERNAME }}/login-app:${{ github.sha }}

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/login-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/login-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v2
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      env:
        KUBECONFIG: /home/runner/.kube/config
      run: |
        mkdir -p /home/runner/.kube
        echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
